04-22-2020, 02:37:29 ERROR while generating report: Traceback (most recent call last):
  File "monitor.py", line 309, in reportThread
    addReportTable(timestamp, deallocatedVms, timesDeallocated, logons, logoffs, vmByRegion, users)
  File "monitor.py", line 252, in addReportTable
    with engine.connect() as conn:
NameError: name 'engine' is not defined
04-22-2020, 02:44:16 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 164, in monitorVMs
    timesDeallocated += 1
NameError: name 'timesDeallocated' is not defined
04-22-2020, 02:47:33 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:47:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:47:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:47:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:47:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:48:59 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:05 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:16 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:22 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:33 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:49:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:31 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:48 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:50:59 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:05 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:22 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:33 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:51:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:14 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:31 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:52:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:10 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:21 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:38 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:53:55 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:00 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:50 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:54:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:41 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:55:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:21 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:38 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:56:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:00 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:57:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:24 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:41 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:52 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:58:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:03 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:20 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:31 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:37 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:48 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 02:59:59 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:05 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:16 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:22 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:33 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:44 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:50 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:00:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:01 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:07 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:18 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:24 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:29 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:35 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:41 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:46 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:52 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:01:57 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:03 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:14 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:20 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:31 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:02:59 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:10 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:21 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:27 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:38 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:03:55 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:01 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:40 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:04:57 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:41 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:05:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:21 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:38 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:06:55 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:00 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:40 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:07:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:24 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:35 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:41 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:52 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:08:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:20 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:37 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:09:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:01 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:18 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:29 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:35 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:40 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:46 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:10:57 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:14 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:11:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:10 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:15 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:21 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:38 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:12:55 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:00 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:40 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:13:57 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:02 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:13 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:19 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:30 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:36 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:47 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:53 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:14:59 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:04 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:10 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:16 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:21 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:27 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:38 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:44 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:15:55 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:01 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:07 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:18 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:24 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:29 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:35 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:40 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:46 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:52 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:16:57 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:03 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:14 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:20 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:31 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:37 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:42 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:48 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:17:59 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:05 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:16 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:22 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:27 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:33 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:44 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:50 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:18:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:01 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:07 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:18 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:24 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:29 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:35 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:41 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:46 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:52 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:19:58 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:03 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:09 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:14 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:20 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:26 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:32 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:37 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:49 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:20:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:00 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:06 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:12 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:23 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:29 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:40 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:46 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:21:57 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:03 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:08 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:14 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:20 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:25 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:31 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:37 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:43 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:48 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:22:54 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:00 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:05 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:11 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:17 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:22 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:28 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:34 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:39 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:45 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:51 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
04-22-2020, 03:23:56 ERROR for VM Demo8: Traceback (most recent call last):
  File "monitor.py", line 150, in monitorVMs
    lastActive = datetime.strptime(vm['last_updated'], '%m-%d-%Y, %H:%M:%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '04/22/2020, 02:47' does not match format '%m-%d-%Y, %H:%M:%S'
